FROM python:3.10-slim

RUN mkdir /ylab_app_test

RUN pip install --upgrade pip

WORKDIR /ylab_app_test

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["pytest app/tests"]
EXPOSE 8000
